const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.TileMovement,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Plugins.Tilemap,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.TileMovement.Acts.SetSpeed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Variables: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{btnDown: 0},
	{btnLeft: 0},
	{btnMenu: 0},
	{btnReset: 0},
	{btnRight: 0},
	{btnSound: 0},
	{btnUp: 0},
	{cell_repeat: 0},
	{win: 0},
	{ScrollTo: 0},
	{gamemanager: 0},
	{posY: 0},
	{TileMovement: 0},
	{Solid: 0},
	{number: 0},
	{plus: 0},
	{target: 0},
	{Tween: 0},
	{target_win: 0},
	{tilemap: 0},
	{transition: 0},
	{tutorial: 0},
	{name: 0},
	{txtUI: 0},
	{Nivel: 0},
	{Sine: 0},
	{btnNivel: 0},
	{levels: 0},
	{txtBtnNivel: 0},
	{btnPlay: 0},
	{Anchor: 0},
	{Game_Tittle: 0},
	{Buttons: 0},
	{LEVEL: 0},
	{Win: 0},
	{mag: 0},
	{dur: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newLayer: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0}
];

self.InstanceType = {
	Variables: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	btnDown: class extends self.ISpriteInstance {},
	btnLeft: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnRight: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	btnUp: class extends self.ISpriteInstance {},
	cell_repeat: class extends self.ITiledBackgroundInstance {},
	gamemanager: class extends self.ISpriteInstance {},
	number: class extends self.ISpriteInstance {},
	plus: class extends self.ISpriteInstance {},
	target: class extends self.ISpriteInstance {},
	target_win: class extends self.ISpriteInstance {},
	tilemap: class extends self.ITilemapInstance {},
	transition: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	btnNivel: class extends self.ISpriteInstance {},
	levels: class extends self.ISpriteInstance {},
	txtBtnNivel: class extends self.ISpriteFontInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	Game_Tittle: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}